"""initial schema

Revision ID: 244fab189cf5
Revises: 
Create Date: 2026-07-27 21:12:32.056881
"""
from alembic import op
import sqlalchemy as sa


revision = '244fab189cf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.String(length=600), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_published_at'), ['published_at'], unique=False)

    op.create_table('case_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_studies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_studies_slug'), ['slug'], unique=True)

    op.create_table('content_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_blocks_key'), ['key'], unique=True)

    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_name')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('service_interest', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('new', 'contacted', 'closed')", name='lead_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('portfolio_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('tech_pills', sa.JSON(), nullable=False),
    sa.Column('youtube_video_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('short_description', sa.String(length=320), nullable=False),
    sa.Column('client_problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('cta_label', sa.String(length=80), nullable=False),
    sa.Column('cta_context', sa.String(length=120), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=700), nullable=True),
    sa.Column('intro_video_url', sa.String(length=500), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slideshow_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=700), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slideshow_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slideshow_images_sort_order'), ['sort_order'], unique=False)

    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=180), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='testimonial_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonials')
    with op.batch_alter_table('slideshow_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slideshow_images_sort_order'))

    op.drop_table('slideshow_images')
    op.drop_table('site_profiles')
    op.drop_table('services')
    op.drop_table('portfolio_projects')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))

    op.drop_table('leads')
    op.drop_table('feature_flags')
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_blocks_key'))

    op.drop_table('content_blocks')
    with op.batch_alter_table('case_studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_studies_slug'))

    op.drop_table('case_studies')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_published_at'))

    op.drop_table('blog_posts')
    # ### end Alembic commands ###

